import { Geist, Geist_Mono, Figtree, Urbanist } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/Topbar";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} ${urbanist.variable} ${geistSans.variable} ${geistMono.variable} font-figtree antialiased`}
      >
        <div className="font-figtree items-center justify-items-center min-h-screen pb-20 gap-16">
          <header className="flex flex-col w-full">
            <Topbar />
            <Navbar />
          </header>
            {children}
        </div>
      </body>
    </html>
  );
}
